name: Deploy Docker

on:
  push:
    branches: [main]
  release:
    types: [released, prereleased]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            hexaaagon/lophura:${{ github.event_name == 'release' && 'latest' || 'canary' }}
          platforms: linux/amd64
      